apiVersion: 1

deleteDatasources:
- name: ElasticsearchLogstash
  orgId: 1

datasources:
- name: ElasticsearchLogstash
  type: elasticsearch
  access: proxy
  database: "logstash-*"
  url: http://elasticsearch:9200
  jsonData:
    timeField: "@timestamp"
  editable: true
